name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusableworkflow.yml
    with:
      message: "Hello, world!"